#!/usr/bin/env bash

# This file is part of "bash -c <...> # Web Shell"
# (see <https://github.com/2011-02-21-bash-c-web-shell/bash-c-web-shell>).
#
# "bash -c <...> # Web Shell" is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# "bash -c <...> # Web Shell" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with "bash -c <...> # Web Shell".  If not, see <http://www.gnu.org/licenses/>.

echo "Content-Type: text/plain;charset=utf-8"
echo 

enable=0
. "$0.conf"
if [ $[enable] = 0 ]
then
    exit 1
fi

quote () 
{
    echo \'${1//\'/\'\\\'\'}\'
}

strip_slashes () 
{
    param="$1"
    param="${param//&/&0}"
    param="${param//\\\\/&1}"
    param="${param//\\/}"
    param="${param//&1/\\}"
    param="${param//&0/&}"
    
    echo "$param"
}

if [ "$key" = "" ] || [ "$PATH_INFO" != "/key/$key" ]
then
    echo "*** Invalid Key ***"
    
    exit 1
fi

if [ $# != 0 ] && [ $# != 1 ]
then
    echo "*** Invalid Arguments ***"
    
    exit 1
fi

if [ $[strip_slashes] != 0 ]
then
    cmd="$(strip_slashes "$1")"
else
    cmd="$1"
fi

if [ "$cmd" != "" ]
then
    if [ $[niceness] != 0 ]
    then
        bash_wrap=("nice" "-n" $[niceness] "bash")
    else
        bash_wrap=("bash")
    fi
    
    echo "*** begin ***: $(quote "$cmd")"
    cd
    "${bash_wrap[@]}" -c "$cmd" 2>&1
    echo "*** end ***"
else
    echo "*** nothing to do ***"
fi

true

